### PR TITLE
update to latest Unity Editor, fixes #28

### LINKED ISSUE #28: Project should use latest release of 2019.4
**Short description**
The base project should be the latest release of 2019.4.  That way, new users aren't prompted to update the project:

image

**To Reproduce**
Clone and open.

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by ciro-unity** [comment]
Hey @tacman, we will upgrade the project soon to the latest version, but as stated in the [Contribution Guidelines](https://docs.google.com/document/d/1PwBF4yQl69RxvVHZ2m2iiy5pYjd9QO-VcuXWDjB7QwA/edit#heading=h.a88pwl4zo9h1), please don't update Unity or Packages version yourselves.

Thanks.

**Comment by tacman** [comment]
Oops, missed that!

**Comment by midopooler** [comment]
Hi @ciro-unity , Its mentioned in the README.md that this project version is 2019.4 LTS and whatever is the latest release. 
But I checked through my Unity Hub that version is 2019.4.7f1. whereas the latest release is of 2019.4.11f1
Now either you update the docs or either let me do that with a tiny PR. What's your opinion?

**Comment by ManuelRauber** [comment]
If you read the contribution guidelines it reads, that the Unity Staff will take care of updating the version. 

--

Beste Grüße 

Manuel Rauber

**Comment by midopooler** [comment]
Sorry, its seems like you didn't get what I'm trying to say. I'm not asking you to change the unity version for the project. 
I want you to update the readme, clearly saying that this project is built on 2019.4.7f1. That's it.

**Comment by ciro-unity** [comment]
> Now either you update the docs or either let me do that with a tiny PR. What's your opinion?

I don't think it's necessary to specify the patch version in the Readme, that would require us to update it manually. The version can be deducted from the file in ProjectSettings.

**Pull request closed without merging**
