### PR TITLE
Added SlimeCritter Model and new Toon variant for Slime Fresnel shinning

### PR DESCRIPTION
**Pull request by treivize**
Forum: https://forum.unity.com/threads/slime-critter.1005712/
Codecks cards: [3D Model](https://open.codecks.io/unity-open-project-1/decks/16-3d-shading/card/187-3d-model)
                         [Tecturing](https://open.codecks.io/unity-open-project-1/decks/23-texturing-ui-2d/card/189-texturing)

The aim of this PR is to add the 3D Model for the slime critter. So as to shade it like specified in the concept art, I have also added a Toon_Fresnel shader where a specular colored Fresnel+Step effect is added to the color channel of the unlit master node.

Concept art:
image

Unity Asset:
image

Toon_Fresnel shader:
image

### CODE REVIEW

**Comment by treivize** [comment]
[SlimeCritterBlender.zip](https://github.com/UnityTechnologies/open-project-1/files/5563569/SlimeCritterBlender.zip)

The Blender file with the 3D Model

**Comment by treivize** [comment]
slime_critter_2
Fresnel Shader updated based on erizzo comments

**Comment by treivize** [comment]
5 Slime Critters prefab variants:
slime_critter_4

New version of the Toon_Fresnel shader:
image

**Comment by ciro-unity** [comment]
The PR seems a bit broken. The Prefabs have the default Lit material, and the materials in the `/Art` folder are also not configured.
image

The shader Toon_Fresnel is under the wrong grouping:
image
(should be UOP1)

What is the "Normal from Height" node doing in the graph?
Also, it feels like the shader is a bit overcomplicated for what it does. Especially in the configuration in the inspector, the parameters have doubled!

**Comment by treivize** [comment]
@ciro-unity, sorry indeed it was quite a mess... FBX export was not good also (wrong rotation and wrong scale...) 
Everything should be fine now. The graph of Toon_Fresnel has been simplified too:

image
2 inputs to control the Fresnel effect (color and tickness)
2 inputs to control the blobby effect (speed and scale)

I have also moved the specular to ToonLightingModel

**Comment by treivize** [comment]
Reworked the specular computation to simplify it and output it separately in Lighting model to be able to add the specular contribution after the albedo multiply node.

**Comment by ciro-unity** [comment]
Great work! I'm merging it!
I have some requests though, mainly around the shader. I'll bring them to the forum thread.

**Pull request merged**
