### PR TITLE
Setup automatic linting as a Github Action

### PR DESCRIPTION
**Pull request by MileyHollenberg**
**What?**
Adding an automatic linter to the project through Github Actions

**Why?**
In order to enforce IDE agnostic style-guide enforcement it's better to run this when you push code to a branch rather than relying on IDE specific implementations. Note that having IDE level support would be valuable still but we need to find a method that works for all major IDEs and isn't tied to a specific one.

**How?**
Through adding a Github Action I implemented the [dotnet-format](https://github.com/dotnet/format) linter in order to automatically format the code. After changes have been made it will add and commit those changes to the current branch. All the user has to do is pull these latest changes in order to be up to date again. 

**Why not do this inside an IDE?**
Eventually we will want that as well, the main concern is that we need to find a way to support the broadest amount of IDEs as some may not have a specific linter whilst others do. We can't assume nor enforce that everyone will be using the same IDE so for now it's better to ensure linting is done remotely whilst we look at a way to implement this locally.

**Where is the style-guide?**
This is currently still being discussed internally but it should be ready soon, keep an eye out on the forum :)

### CODE REVIEW

**Comment by MileyHollenberg** [comment]
Just noticed that the Github Actions bot does not have the ability to sign the CLA, I'll setup a separate account for this tonight and use that instead

**Comment by StanislavChankovSellerCloud** [comment]
@MileyHollenberg good one, but it duplicates in some way my PR 
https://github.com/UnityTechnologies/open-project-1/pull/71

**Comment by StanislavChankov** [comment]
@MileyHollenberg , this seems to be super cool idea. I am not sure whether it work, but we definetely wants this as well.
Q: How we will clear the commits from the Github Actions, since they will be meaningless for the code/logic?

**Comment by MileyHollenberg** [comment]
The Github Actions bot will be replaced with a different account, they will indeed not have any meaningful effect on the code itself but from what I can see so far in the commit history is that all PRs have been squashed meaning the bot probably won't even show up after a PR has been merged.

Also I will be updating this PR tomorrow, upgrading my PC took a bit more time than expected

**Comment by StanislavChankov** [comment]
@MileyHollenberg , you could read and share your thoughts about DI - [](https://forum.unity.com/threads/dependency-injection.983484/)

**Comment by ciro-unity** [comment]
Great contribution, Miley!

**Pull request merged**
