### PR TITLE
Save system

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
I just created an simple Save System. It is completely described in the corresponding thread:
https://forum.unity.com/threads/save-system.1056311/

### CODE REVIEW

**Comment by HarshNarayanJha** [comment]
For conflicts @ciro-unity, How will I fix them?

**Comment by vjs22334** [comment]
You need to sync your fork with the main project. Here is how : https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork. you will get a merge conflict in InteractionManager.cs since it was changed both by you as well as in this repo. You will have to manually merge the code in that class and commit it again.

**Comment by HarshNarayanJha** [comment]
Thanks again @vjs22334, I answered in forum.

**Comment by ciro-unity** [comment]
Yeah, the PR needs cleanup before we can check if it works.

**Comment by HarshNarayanJha** [comment]
Do You mean I have to checkout to the save-system branch and then pull from the main branch?

**Comment by HarshNarayanJha** [comment]
Ok, the conflicts now are resolved. Now @ciro-unity can check it.

**Comment by bzgeb** [comment]
I haven't fully reviewed the PR, but I see that you're using BinaryFormatter and I just want to mention that nobody should ever be using binary formatter.  There's a long explanation [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide). Realistically it's a minor threat in our little game, but it's important that we learn and promote good practices.

**Comment by bzgeb** [comment]
I'll be using the code from [this PR](https://github.com/UnityTechnologies/open-project-1/pull/286) as a base for the save system (it covers the underlying save system rather than a gameplay implementation). As for this PR, it's difficult to merge with confidence because it touches a lot of files, including several scene files and prefabs, but I have your code now and I'm going to repurpose it into the final system.

**Pull request closed without merging**
