### PR TITLE
A Wooden Bench for sitting and eating. 

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
Do you have a forum thread linked to this PR? 
 https://forum.unity.com/threads/regarding-art-assets-and-music.980892/page-3

What will this PR bring to the project for everyone?  
A Wooden Bench

Why are these changes necessary?  
Yes, it will allow characters to sit and eat.

### CODE REVIEW

**Comment by HarshNarayanJha** [comment]
I have also created a Prefab of it(UOP1_Project/Assets/Prefabs/Props/WoodenBench.prefab)
Talk

**Comment by ciro-unity** [comment]
I checked the bench, looks good. A couple of requests before I merge it:

image

- Can you move the pivot of the object to the ground? (see in the picture) Also if the three parts could be merged into one mesh, it would be great.
- The bench is huge! Can you scale it to 0.4? Then the characters would be able to sit on it.
image

- Finally, it would be nice if you could create PrefabVariants instead of simple prefabs.
image

Thanks!

**Comment by HarshNarayanJha** [comment]
Ok, it's done.

- I merged all into one mesh and moved it's pivot point to the bottom ground.
- I scaled it down to 0.4
- I created a Prefab variant last time also. And created variant this time also, but changed its folder. I thought the Bench's folder would be more suitable in `Prefabs/Furniture` than `Prefabs/Props`

Now let us see what our game characters say:
Talk2

Thanks,  any other suggestions will be welcomed.
Regards, Harsh.

**Comment by HarshNarayanJha** [comment]
Lastly, I thank to @Smurjo for the texture painting work.

**Comment by ciro-unity** [comment]
Merged!

**Pull request merged**
