### PR TITLE
Character Controller / State Machine

### PR DESCRIPTION
**Pull request by islesofurth**
This is a basic Character controller for  MR Piggy.
I'm self taught & only been coding a little bit, so anything that could be improved please comment.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PiggyController : MonoBehaviour
{
    public GameObject player;
    public bool grounded;
    public bool canJump;
    public bool jumping;
    public bool canInteract;
    public bool canAttack;
    public bool invul;
    
    public Animator anim;
    public Rigidbody rb;
    public CapsuleCollider capCollider;
    public int jumpForce;
    public int moveSpeed;
    public int energy;

    
    

    void Start()
    {
        canJump = true;
        grounded = true;
        canAttack = true;
        jumping = false;
        canInteract = false;
        invul = false;
    }

    public void FixedUpdate()
    {
        

        
        while (invul == true)
        {
            capCollider.enabled = false;
        }

        // Idle State
        if (moveSpeed == 0 && jumping == false)             
        {
            anim.Play("idle");
        }

        
        // Move State
        if (Input.GetAxis("Vertical") > 0)
        {
            rb.AddForce(Vector3.forward * moveSpeed);
            anim.Play("moving");

        }
            else if (Input.GetAxis("Vertical") < 0)
            {
                rb.AddForce(Vector3.back * moveSpeed);
                anim.Play("moving");
            }

        if (Input.GetAxis("Horizontal") > 0)
        {
            rb.AddForce(Vector3.left * moveSpeed);
            anim.Play("moving");
        }

        else if (Input.GetAxis("Horizontal") < 0)
        {
            rb.AddForce(Vector3.right * moveSpeed);
            anim.Play("moving");
        }

            // Jump State
        if (Input.GetButtonDown("Jump") && canJump == true && grounded == true)
        {
            
            jumping = true;
            rb.AddForce(Vector3.up * jumpForce);
            anim.Play("jumping");
            Invoke("JumpDelay",1);
            canJump = false;
            grounded = false;
        }

        // Attack State

        if (Input.GetButtonDown("Attack") && canAttack == true)
        {
            anim.Play("attacking");
            canAttack = false;
            Invoke("Attackdelay",0.5f);
        }

        
        // If pause is done here  
        if (Input.GetButtonDown("Pause"))
        {
            // reference the paused command
        }

    }

     
    private void OnTriggerEnter(Collider other)
    {
        // Fainted State || Game Over
        if (energy <= 0)
        {
            invul = true;
        }
        
        // Hit State
        else if (invul = false && capCollider.gameObject == player)
        {
            energy --;
            invul = true;
            Invoke("InvulDelay", 1);
        }
        
        
    }
        
    void JumpDelay()
    {
        canJump = true;
    }

    void AttackDelay()
    {
        canAttack = true;
    }

    void InvulDelay()
    {
        invul = false;
    }
}
`

### CODE REVIEW

**Comment by DeivSky** [comment]
Hey, I think you're trying to merge the wrong fork, you're merging Unity's Scene-Loading fork instead of your own!

As for your script, that's not a State Machine. That's actually the kind of implementation a State Machine aims to avoid, which is having a bunch of booleans and if/else statements all over the place to determine the behaviour of an object. Rather, in a State Machine, each state is represented as a separate object with its own behaviour. The State Machine would then hold a reference to the current state and call on that state's actions. When the conditions to swap to a different state are met, we simply set the current state to the new state and now we're calling on that state's actions.
[Here's a much better explanation](https://refactoring.guru/design-patterns/state).

Also, I think this would probably cause a StackOverflowException or freeze the client for a long, long time.
```
    while (invul == true)
    {
        capCollider.enabled = false;
    }
```

**Comment by islesofurth** [comment]
> Hey, I think you're trying to merge the wrong fork, you're merging Unity's Scene-Loading fork instead of your own!

Ya, it wouldnt let me create the Pull Request without selecting from the 2 drop downs.


> As for your script, that's not a State Machine.

From your description & From everything I Google, A state machine uses an Enum.
So why doesn't anyone use an Enum in the PR's they are providing?
Also An Enum still needs bools to work or things don't turn off.
So in other words, this meant to be the foundation (whats the point of an open project if one person does everything)

> Also, I think this would probably cause a StackOverflowException or freeze the client for a long, long time.

No offense but did you even read this? or did you just see the  "  while  "
Turning off the players collider could only at worst make the player unable to take damage. It would not crash anything...

**Comment by davejrodriguez** [comment]
> Turning off the players collider could only at worst make the player unable to take damage. It wont crash anything.

Sure, until someone coding a power-up in another part of the project sees that they can set invul to true on PiggyController.
> So why doesn't anyone use an Enum in the PR's they are providing?

They are, in a way. Using an enum _would_ work, but to add/remove states you must edit the enum in code. Not very designer friendly. Most other FSM PRs that I've seen have opted to make a State base class that inherits from ScriptableObject. Designers can create/delete states as _assets_ of the project and plug them in where needed. Essentially, Walking, Jumping, Fainted etc. assets are options of the State enum.

Your PR is what this [Unity Learn tutorial on state machines](https://learn.unity.com/tutorial/managing-state?uv=2019.3&projectId=5db812ecedbc2a0020e271cb#5db81a32edbc2a002013481a) literally calls the "naive approach to managing state". I'd definitely recommend going through that whole tutorial. Once you finish that tutorial, [Pluggable AI](https://learn.unity.com/tutorial/pluggable-ai-with-scriptable-objects) is a great next step.

As for correctly submitting PRs, please check out this video by [Dapper Dino](https://www.youtube.com/watch?v=lYAHmthUO1M). Follow those steps and you should be golden with your next PR.

**Comment by DeivSky** [comment]
> From your description & From everything I Google, A state machine uses an Enum.

I never mentioned enums. Did you read the link I sent you?

> So in other words, this meant to be the foundation

And what I meant was that it is not a good foundation. Whenever a new state needs to get added we'd have to go and add more bools, more if/else statements, etc. It'd soon become a 500+ lines piece of code that no one would understand. A State Machine is meant to be easily extensible. 

>  (whats the point of an open project if one person does everything)

I totally agree, that's why I'm checking other people's PRs and giving my insight. 

>No offense but did you even read this? or did you just see the " while "
Turning off the players collider could only at worst make the player unable to take damage. It wont crash anything.

As @davejrodriguez said, `invul` is public. Also you're still freezing the client for one second when doing this ` invul = true; Invoke("InvulDelay", 1);`

>Edit: Sorry If any of this comes off as offensive, I dont mean to be rude, I am just passionate about my work as I am sure everyone else is. I did ask for feedback & I thank you for your time & oppinion you provided.

Yes, everyone is passionate about their work. Don't take it so personal though, you did say you were just starting to learn. If someone tells you you're doing it wrong, chances are you are. If you really think you're doing it right, do some research and provide evidence. Send me any of those links you found on google where it says a StateMachine has to use Enums. You probably misinterpreted them just like you misinterpreted my definition. 

We're all learning from each other, that's what this project is about.

**Comment by islesofurth** [comment]
> Sure, until someone coding a power-up in another part of the project sees that they can set invul to true on PiggyController.
I see your point here.
Refrencing code that has already been created, but it not executing in the intended way.
I can see this would definately be a problem for team projects.

Thanks for the tutorials, I will do them both right after I watch that PR video :P


> I never mentioned enums. Did you read the link I sent you?
Yes, I read your link.
I do know what a state machine is, but I had my own assumptions.
I only did a little research, as it was not providing any results theat were unknown. (such as scriptable objects)
Google also supprisingly showed almost exclusivly enums when googling state machine. 
(of course it could have been all i was able to see) 
So it certainly made me think it was the best or at least most common ussage.

> invul is public.
This is a good point, if it was private there wouldnt be a problem.
I shouldn't default to making everything public.


Thanks for your help

**Comment by ciro-unity** [comment]
Given the fact that we already have several state machine implementations and this PR is targeting the wrong branch, I'll close it.

> Ya, it wouldnt let me create the Pull Request without selecting from the 2 drop downs.
That's weird. You probably haven't forked the repo. As the others said, check out @DapperDino's video on the process.

Also check out some of the other state machine implementations, @islesofurth! And don't be discouraged :)

**Pull request closed without merging**
