### PR TITLE
Bugfix - Updated "Light and Shadows" subgraph for 0 light, added default

### PR DESCRIPTION
**Pull request by Tatranskymedved**
Updated "Light and Shadows" subgraph to check whether there is some light and if none, supply full light.

Card: https://open.codecks.io/unity-open-project-1/decks/13-bugs/card/193-objects-are-black-when-the-scene-is-not-baked
Issue: https://github.com/UnityTechnologies/open-project-1/issues/206

**Short description of issue**
All objects (both dynamic and static) are black when dragged into a new scene.

**Resolution**
Shader sub-graphs are currently taking light from Baked GI and Main Light color. If they are missing, there is no light on the scene and characters/objects are dark. This PR is adding step in the sub-graph of "Lights and Shadows" to check whether there is full black (0,0,0) and if so, add full light on the character/object.

image
image

### CODE REVIEW

**Comment by Tatranskymedved** [comment]
To clarify, I was originally thinking to add this light value only to the Baked GI, however it would not produce light on the dynamic objects/characters. I assume we want to have them lightened all up thus added the light at the end of sub-graph.

**Comment by treivize** [comment]
Why not moving your any + branch just after the Baked GI node? Because here you loose completely the directional light information.  And maybe reduce also the fake illumination contribution (1 -> 0.5) to not over saturate the final rendering.

**Comment by Tatranskymedved** [comment]
> Not sure why it not working to move your any + branch just after the Baked GI node. Because here you loose completely the directional light information.
> 
> And maybe reduce also the fake illumination contribution (1 -> 0.5) to not over saturate the final rendering.

If I would move supply light (Any+Branch with Color(1)) just after Baked GI, dynamic objects and character (that are not static) would have 0 light and would be completely black.

I agree that I can limit the light provide just to 0.5, but this value should get to actual result only when there is complete 0 of main light/baked light. Will that every occur in game scenes?

**Comment by treivize** [comment]
I thought you were maybe on Discord, but I have checkout your PR on my local and move the any+branch close to the Baked GI node. And it is working fine for static and dynamic objects on a new scene with a directional light: 
image
image
which other problem do you try to solve exactly?

**Comment by Tatranskymedved** [comment]
As mentioned on Discord, if we put this Any+Branching pair just after Baked GI, dynamic objects (which are not Baked) will have 0 light. Once you remove Directional light, it will get completely dark.

Should there always be some Main light / Baked GI available? E.g. if we enter building or some cave? If not then the objects might get completely dark and it would make sense to move this Branch pair just after Baked GI. But if this will practically never occur, this solution shouldn't cause any troubles/prevent any light information loss.

So Q is: "What are we trying to achieve with this?". Afaik it is only that we want to see objects when there is no light.

**Comment by ciro-unity** [comment]
Thanks a lot for the PR @Tatranskymedved!

As a first thing, I'd say that we don't need the fix for baked objects, because if they are baked, they work. If light is not baked, then they are dynamicly lit. So we need to fix it only for dynamic objects.

Note that here by static/dynamic I don't just mean whether the Static flag is on/off, I mean if the object has participated in a baking process. Obviously participating in the bake is done with the above checkmark, but until you press "Bake", all object are dynamicly lit regardless of their static flags.

**Comment by ciro-unity** [comment]
The other thing is, I've been told that the Branch node is one to avoid, if you can. When the compiler is able to, it is transformed in a math operation. For instance if it can translate the `false` as `*0` and the `true` as `*1`, but if it can't, it will insert an `if` which apparently is very underperforming for shaders. So any fix we choose, I'd avoid the branch node.

Do you want to fix it or do you want me to do it?

**Comment by Tatranskymedved** [comment]
Hey @ciro-unity ,

I hope I've understood this correctly. We just need to add some fake bakedGI if there is none. Doing this, it should add some kind of light/color for all objects and the rest of lightning will be done by the rest of light (main lights etc.). And as your last comment mentioned to avoid branching, I've changed it to use `Maximum` node. 

updatedBakedGI

**Comment by treivize** [comment]
This problem remembered me a video I have seen few months ago: [Branchless Programming](https://www.youtube.com/watch?v=bVJ-mWWL7cE)
Based on this approach, I would go for this way of swapping Baged GI to a default global lightning contribution:

image

**Comment by ciro-unity** [comment]
I assume that's the way, I can't be 100% sure if we don't have it in the graph and test it. If you'd want to make the change then we can see if it works.

**Comment by ciro-unity** [comment]
Hey @Tatranskymedved, a million apologies for coming back to this so late. In the end there is a very similar PR from @treivize which I am going to pull in since it's a very simple solution - which is always preferable.

However, I've done a bit of Git gymnastics so I could pull your commit too, in order to show you as a contributor too. I think you deserve it, the discussion happening here was very interesting!
Hope to see you in another PR :)

**Pull request merged**
