### PR TITLE
fix: Project won't compile due to a reference to UnityEditor (#157)

### PR DESCRIPTION
**Pull request by tarasov65536**
Is this PR linked to an issue? If so please link it here, if not please create one first, then link it.
[#157](https://github.com/UnityTechnologies/open-project-1/issues/157) 

Is there a forum thread linked to this issue? If so please link it here. 
No 

How did you resolve this issue?  
I reorganized **ClieckToPlaceHelper** and **SpawnLocationEditor** classes in the way when all editor-dependent functionality were placed in **SpawnLocationEditor** class in Editor folder. 

How can it be verified that the issue has actually been resolved?  
Just try to build project and check there is no compilation errors.

### CODE REVIEW

**Review by GFX5000i — CHANGES_REQUESTED** [review]
Great fix! The Component still works as intended and the project is compiling.

I suggest these minor changes to improve the code readability and compliance to the conventions:
- The _UnityEditor_ reference is unused so it's corresponding _using_ should be removed.
- The __targeting_ variable and it's property _targeting_ can be refactored in a single line using:
`public bool IsTargeting { get; private set; } = false;`
- The private variable _helper_ should be __helper_. As a personal preference I would rename to __clickHelper_ for extra clarity.

**Comment by tarasov65536** [comment]
@GFX5000i, thx for review. I've implemented this changes.

**Comment by ciro-unity** [comment]
Thanks for the fix, @tarasov65536, and nice first contribution!

If you are on the Unity Discord and you want to be given the Open Projects Contributor role, let me know your nickname here!

**Comment by tarasov65536** [comment]
@ciro-unity thx for merge.

I've joined to Unity Discord and have the same name there **tarasov65536#3564**

**Pull request merged**
