### PR TITLE
Inventory system

### PR DESCRIPTION
**Pull request by VAD37**
Forum Link: https://forum.unity.com/threads/inventory-system.980646

### What will this PR bring to the project for everyone?

InventoryDatabase is just simple ID point to ScriptableObject.
All ItemData point to a prefab as logic content.
Include Sample code for intended framework code design purpose.

Included Custom Editor support for designer friendly.
image

### Why are these changes necessary?  
We have other PR for inventory system but it based on Inheritance BaseItem.

In long run, when more itemType added to game. It will make refractor other System depend on predefined ItemType harder.
This PR address that issue by make sure all Item become Data. Other system have to write more code to handle ItemType check, but it will much easier to maintain for less experience programmer.

### CODE REVIEW

**Comment by ciro-unity** [comment]
Hey @VAD37, I kind of like the system but I feel like it adds a lot of code between Inspector code, examples and other.
The Inspector is cool, but it seems redundant: the inventory is going to be filled by script, not by a designer.

This said, I think we should have the reorderable list Inspector UI in the project. Could you make it into a separate PR, maybe?

**Comment by VAD37** [comment]
You was right about the system too complex and totally not fit for current project.

Sure, I can help with the inspetor and custom editor part. 
Do you want to request anything else? I will look all of its over weekend.

**Comment by VAD37** [comment]
#100 would be more close to what project need. Closed.

**Comment by ciro-unity** [comment]
Thanks @VAD37.

Are you on Discord? I'd like to give you the role of Open Project Contributor in any case. Let me know your nickname if you care about it.

**Pull request closed without merging**
