### PR TITLE
[WIP] Simplified Input to use Composite

### PR DESCRIPTION
**Pull request by davejrodriguez**
Issue: #245
Forum: https://forum.unity.com/threads/mouse-pointer-erratic-behaviour.1014424/#post-6581881

The way we are currently going into and out of "rotate camera mode" via a separate right mouse button action that is _only_ for setups with a mouse is not really the best way to utilize the Input System. I'm unable to reproduce the bug on my machine, but my theory is that switching modes like this is causing the erratic mouse behavior.

A better way is to use a composite where you use the right mouse button as a trigger and output the mouse delta as the delta. Then you can set the composite as a binding of the singular camera rotate action instead of several mouse specific actions. So I've made a composite called DragComposite (I made this previously in #83, but we were unsure then if mouse drag was desired) which takes a button "trigger" and a Vector2 "delta". This is easily reused and modified.

I have also modified the CameraManager, InputReader, and TestingGrounds scene to work with these changes.

To verify:
1. Play TestingGrounds.
2. Right click and drag to rotate mouse.

### CODE REVIEW

**Comment by ErikBehar** [comment]
you removed the cursor lock, so I can't repro the bug, because the thing causing the bug is removed. I assume we still want the cursor lock / hiding the cursor.

**Comment by davejrodriguez** [comment]
Sure, makes sense. I'll add it back in with this solution.

**Comment by ciro-unity** [comment]
Where are we with this PR? I think @ErikBehar's fix solved the mouse issue (although we need some testing of course!)

**Comment by davejrodriguez** [comment]
> Where are we with this PR? I think @ErikBehar's fix solved the mouse issue (although we need some testing of course!)

Still working on getting cursor lock and visibility back in. It's certainly harder without the extra action, but I think it's worth the trouble, especially when we start implementing rebinding logic. This PR should probably be considered an enhancement rather than a bug fix now that @ErikBehar fixed it in his PR.

**Comment by ciro-unity** [comment]
Sounds good. Just be aware that there were some changes to the `CameraManager` recently (shouldn't conflict with your code).

**Comment by ciro-unity** [comment]
Is it still a work in progress?

**Comment by davejrodriguez** [comment]
Not active progress. I will close for now.

**Comment by ciro-unity** [comment]
Just out of curiosity, so the issue with your implementation was that we lost the control over the cursor?
For the rest it was working...?

**Comment by davejrodriguez** [comment]
The issue is that in my efforts to simplify the camera rotate actions (one specifically for mouse) with a single composite, I made it harder to enable/disable cursor lock and visibility at the right times. I think it's possible and still think it's cleaner than having a dedicated camera mode action. But until I can get it working with the desired cursor functionality, I'll refrain from clogging up the open PRs :)

**Pull request closed without merging**
