### PR TITLE
Added Inventory Icons for Banana

### PR DESCRIPTION
**Pull request by arunchahar**
Added inventory icons for fruits - banana. With sizes 64x64, 128x128, 256x256, 512x512

https://forum.unity.com/threads/ui-graphics-item-icons.987537/#post-6833744

It adds an icon for banana fruit with different sizes 64x64, 128x128, 256x256, 512x512.

To add an icon for banana in inventory

Added the icons images

64x64
002_Banana64x64

128x128
002_Banana128x128

256x256
002_Banana256x256

512x512
002_Banana512x512

All images are png

### CODE REVIEW

**Comment by Smurjo** [comment]
Maybe we want to wait with merging until we have some decision concerning the color palette?

**Comment by arunchahar** [comment]
@ciro-unity the CLA is showing pending but i have already signed it. Am i missing something ?

=============================================================

> Maybe we want to wait with merging until we have some decision concerning the color palette?

@Smurjo Yeah. I will update according to the pallete requirements.

I did not received any feedback on sample icons arts for fruits https://forum.unity.com/threads/ui-graphics-item-icons.987537/#post-6832079. As you can see I had to use some extra colors outside of the color palletes.

And I think the color pallete selection will take a long time as you would have to incorporate every single inventory items including 3d models as well as finding the base color, highlight color, shadow color. To get the cartoony feel it could be [base+highlight] OR [base+shadow] or all three.

For current inventory we can do the following:
1. Adding all the icons with colors and then later updating the color pallete.
==OR==
2. Adding the icons outlines without color and then later adding the colors from pallete.

What do guys think ?

**Comment by ciro-unity** [comment]
Hey @arunchahar. I'm sorry but this style of icons is not what we're going for. In fact, we don't know the style yet, but even though the icon is not too bad, we're still looking to incorporate something with a more refined drawing style. (which doesn't necessarily mean more complex)

Plus, we actually don't have a banana in the game!
So I'm closing this one for now. Thanks though.

**Comment by arunchahar** [comment]
> Hey @arunchahar. I'm sorry but this style of icons is not what we're going for. In fact, we don't know the style yet, but even though the icon is not too bad, we're still looking to incorporate something with a more refined drawing style. (which doesn't necessarily mean more complex)

@ciro-unity added new art style here https://forum.unity.com/threads/ui-graphics-item-icons.987537/page-2#post-6889349, if its still not decided then will leave it.

> Plus, we actually don't have a banana in the game!
> So I'm closing this one for now. Thanks though.

Happy to contribute. ^_^

**Comment by HarshNarayanJha** [comment]
Ignore this everyone else...
@arunchahar, wanted to contact you. If you got this notification, need your help here: https://forum.unity.com/conversations/need-help-for-art.593467/

**Pull request closed without merging**
