### PR TITLE
Cleaned up version of Dissolve VFX

### PR DESCRIPTION
**Pull request by recklol**
Hopefully this is fine like this, I created another scene where I can test out effects without interfering with the ArtShowcase scene.

Forum thread:
https://forum.unity.com/threads/burn-disappear-effect.997856/
Card:
https://open.codecks.io/unity-open-project-1/decks/24/card/176-burn-disappear-effect

This is a basic, stylized implementation of a dissolve effect. A shader and a Particle System working together.
These changes are important to give feedback to the player, and also feel satisfying to look at.
I implemented it the best way I could, making it customizable easily.

### CODE REVIEW

**Comment by ciro-unity** [comment]
Looks really good! One thing though that I would like to change is to make the dissolve effect an add-on to the Toon and not part of it. In this sense, something more like what @treivize did in the wind add-on in PR #150. I'll merge that one first and then I'll get on this one!

**Comment by recklol** [comment]
> Looks really good! One thing though that I would like to change is to make the dissolve effect an add-on to the Toon and not part of it. In this sense, something more like what @treivize did in the wind add-on in PR #150. I'll merge that one first and then I'll get on this one!

I'm happy you like it!
Should I make that change, or you will?

**Comment by ciro-unity** [comment]
It would be great if you could! I merged #150 
I also see there's a conflict... I suspect because the two toon shader graphs were broken and lacking the keywords, so I readded them manually. But I think you'd have to discard your file anyway since it's the one you need to rework to create the modularity.

Thanks @recklol!

**Comment by treivize** [comment]
Hello @recklol,

Just to let you know that to progress on delivering your dissolve effect I have opened a new PR to bring it back on an the current code stack. Please do not hesitate to review my changes and let me know if you are fine or now with them.
[new PR](https://github.com/UnityTechnologies/open-project-1/pull/217)

**Comment by ciro-unity** [comment]
I'll close this one then, based on the conversation on the other side. Thanks anyway @recklol!

**Pull request closed without merging**
