### PR TITLE
Plant Critter - Model, UV, Color, Rig and Animations

### PR DESCRIPTION
**Pull request by treivize**
Forum: [Plant Critter](https://forum.unity.com/threads/plant-critter.1005700/)
Codecks card: [Plant Critter Card](https://open.codecks.io/unity-open-project-1/decks/61-game-elements/card/17v-plant-critter-char)

In case you are interested in having a look at the plant critter I made. Any suggestion and comment on it are welcomed in the forum thread!

Ref concept art:
image

Unity asset:
image

### CODE REVIEW

**Comment by ciro-unity** [comment]
I retargeted this PR to the `art-assets` branch (even if that and `main` are pretty much on par)

**Comment by treivize** [comment]
Plant critter updated:
- Model spherified:
image
- UV reworking:
image
- Texture reworking:
image
- Animations (Idle, WakeUp, Alert, Attack) reworked
plant_critter_3

**Comment by treivize** [comment]
Meshed eyes
plant_critter_4

**Comment by treivize** [comment]
New animations:
plant_critter_5

**Comment by treivize** [comment]
Following latest comments from the forum thread, the eyes have been removed. And the animator has been set up with proper triggers:

[Demo](https://youtu.be/t81EFP99P3M)

**Comment by treivize** [comment]
Sorry I did a mistake with git...

**Comment by ciro-unity** [comment]
Such a great addition! So cool! Sorry for taking so long to pull it in.

A couple of notes, not sure if you know:
- I noticed you added transitions in the Animator to the same state. Is that to make the state loop? If so, it's not needed: you can set a clip as looping from the import settings on the .fbx.
image

- I removed the transition from Faint to Exit, otherwise the state machine resets from the start. I think that is a thing you normally use for hierarchical state machines, so you exit from a layer and you give back control to the above one.

- One thin I have to say... "Cube"?!?!?! 😥
image
(we don't need to fix it though)

Anyway, super cool!

**Pull request merged**
