### PR TITLE
Art assets - Fruit and vegetables

### PR DESCRIPTION
**Pull request by Smurjo**
Various food items as ingredients for cooking. 

All assets were modelled in Blender, starting from the textures. The textures were created with GIMP.
artichokes
cucumbers
lemons
onions
oranges
truffles
vanilla
almonds

### CODE REVIEW

**Comment by Smurjo** [comment]
Added ginger

ginger

**Comment by Smurjo** [comment]
Maize

**Comment by Smurjo** [comment]
mangetout

**Comment by Smurjo** [comment]
critterSeeds
rockCritterEggs
slimeCritterEggs

Triangles        texture
slime critter egg yolk   144 
slime critter egg white 182
rock critter egg            228                 512x512
critter seed                  244                 512x512
peeled critter seed      196
chicolade                     750

**Comment by ciro-unity** [comment]
Thanks @Smurjo, this is such a huge amount of great stuff! Thanks a lot!
I love the products of the critters!

**Pull request merged**
