### PR TITLE
Game Settings System. Core functionality.

### PR DESCRIPTION
**Pull request by STARasGAMES**
Implemented basic settings such as  Resolution, FullScreenMode, Graphics, Language, MusicVolume, SfxVolume, InputBindings.
Implemented UI views for existing settings.

Sorry for such a big PR. There is only code, no assets.

The main things to look at:

- Assets/Scripts/Settings/Core - core of the settings system
- Assets/Scripts/Settings/GameSettings.cs - entry point of the settings system
- Assets/Scripts/Settings/Controls - input bindings override
- Assets/Scripts/Settings - implementation of basic settings and their UI

Yes, UI is out of scope according to the card, but I had this functionality before, so just modified(simplified) it for this project specifically.

Card: https://open.codecks.io/unity-open-project-1/decks/15/card/15e-game-settings-system
Forum: https://forum.unity.com/threads/game-settings-system.980703/

### CODE REVIEW

**Comment by STARasGAMES** [comment]
Refactored code to respect programming conventions

**Comment by ciro-unity** [comment]
Same comment as for PR #67, I can't merge this PR just yet because we don't have the UI planned yet. As specified on the card, we are not looking to integrate it with UI just yet.

I'll come back to this once we have the whole UI situation more clear.

**Comment by STARasGAMES** [comment]
@ciro-unity Do I need to remove the UI part? Or you are looking for another solution?

**Comment by Casey-Hofland** [comment]
Hi there, I have a good idea for the UI part, as well as hopefully generalizing the system a bit more. However, I'm unsure how I can contribute to this branch as it hasn't been pulled yet. Things I'd like to do:

1. Make Settings Scriptable Objects. I believe this is helpful for a couple of reasons explained below. 

2. Create a few SettingView Components that... you know it's easier if I just show it:

WIP SettingsToggle 1
WIP SettingsToggle 2

The SettingsToggle has an Editor that uses reflection to find all ISettingToggle's (in all project assemblies). This component is perfect for use by designers who want to tweak quickly. What you see will be changed a tiny bit to pair with ScriptableObjects.

--------
ScriptableObject motivations:
Settings can be manifested (e.g. GameSettings might simply serialize its Setting[] variable and leave the rest to the user), Settings can be dragged and dropped into UnityEvents for simplicity and Settings can be used by anything, even if it's not UI but, like, a physics object or something. Also, ScriptableObjects make saving easier and allow for custom editors (e.g. for AudioSetting). In the end, it just pairs better with Unity.

**Comment by STARasGAMES** [comment]
I don't think SOs are the best fit for game settings. Game Settings System is quite stable in its nature. If something relies on a concrete game setting (for example, AudioSystem may rely on SfxVolumeSetting) then this connection is permanent. There is no scenario when AudioSystem needs another setting other than SfxVolumeSetting.

Moreover, AudioSystem doesn't have to know about Game Settings System at all! 
It's SfxVolumeSetting's responsibility to set values to AudioSystem. 

Why do you need a custom editor for settings? It makes no sense. Any setting is responsible only for storing its value and applying it to the target system (again, like SfxVolumeSetting sets its value to AudioSystem). I can't see any advantages of using custom editors for game settings.

**Comment by Casey-Hofland** [comment]
I'll reply more in-depth later, but SfxVolumeSetting for example is using a const string for the audio mixers exposed parameter. We can set this in the constructor or make a public variable sure, but if it were a ScriptableObject we could write an Editor that can ensure the parameter exists. We can also give the audio mixer to the SfxVolumeSetting itself, instead of the GameSettings, which is great if we have multiple mixers and values we want to tweak (yes, this can then be reused for MusicSetting).

By making it a ScriptableObject we also make it a more powerful tool to extent for other programmers, who might want to manipulate settings from their own scripts which may, again, require references.

**Comment by Casey-Hofland** [comment]
@ciro-unity is it possible to check out features before they've been added? I'd hate to start from scratch and would rather dual-program on Stars repo.
@STARasGAMES with your consent of course. You could also, uhm... send me the files? Sorry, I know that's a bit rude and not really a good solution because we would be working in different repos.

**Comment by STARasGAMES** [comment]
@Casey-Hofland I can send files, sure, why not:)
Let's wait for @ciro-unity answer. Maybe he is thinking about another solution we don't know

**Comment by davejrodriguez** [comment]
@Casey-Hofland you should be able to check out this pull request and push it up to your own repo as a branch. Then you push changes to your own repo and create a pull request on @STARasGAMES PR. At least, that's how I do it. Maybe there is a better way, but shouldn't have to manually send files around I'd think.

**Comment by Casey-Hofland** [comment]
@STARasGAMES I've created a rough implementation with ScriptableObjects so you can check it out and see what you think, but, my bad... I can't push it. I'm not sure what I did wrong, I probably should have forked instead of cloned... either or, would you please add me as a collaborator in your repo?

Also, I think you'll like what I do with GameSettings, I've found a way that it doesn't even have to be static.

**Comment by STARasGAMES** [comment]
@Casey-Hofland I think it's just better and easier to make a fork.

I can't find your implementation. On repo last change 13hr ago

**Comment by Casey-Hofland** [comment]
Sooo... yeah, @STARasGAMES , I gotta come clean I went totally bananas on everything and at a certain point I was like "this isn't even close to the same implementation anymore and it will be easier to review the changes fresh"... so I went out and made my own Fork. The system has been my entire weekend plus this evening after work and I'm pretty happy with it!

I hope I'm not stepping on any toes by doing so. I'm pretty new to being an active part of a community.

**Comment by uChema** [comment]
Hey @STARasGAMES ! 
Thank you for your contribution ! 
Sorry it took us so much to check your PR, we've been working on various other systems before this one. 
Following the [Miro board for User interface](https://miro.com/app/board/o9J_kknB_L0=/) we implemented the settings system using UI Assets from the forums. It's now pushed into main and can be tested in the game.

**Pull request closed without merging**
