### PR TITLE
Applied the tag EditorOnly to logical section GameObjects in the Beach scene

### PR DESCRIPTION
**Pull request by GordonArber**
There was no forum thread for this PR.
This PR updates the scene so that it meets the conventions.
These changes are necessary to keep up with proper conventions.
I selected all the logical section empty game objects and applied the EditorOnly tag to them. I then tested it and everything ran smooth.

### CODE REVIEW

**Comment by ciro-unity** [comment]
I didn't ask, but are you on the Unity discord? I can assign you the Open Projects contributor role if so! (I need the username)

**Comment by GordonArber** [comment]
> I didn't ask, but are you on the Unity discord? I can assign you the Open Projects contributor role if so! (I need the username)

I am actually, **ToxicFume#4046** is my handle and I go by Gordon on the Unity Discord server.

**Comment by ciro-unity** [comment]
Cool, role given!

**Comment by GordonArber** [comment]
> Cool, role given!

Oh great, thank you!

**Pull request merged**
