### PR TITLE
Pathway component with Idea

### PR DESCRIPTION
**Pull request by AlexandreGheraibia**
[Previous pull](https://github.com/UnityTechnologies/open-project-1/pull/371)
[Card](https://open.codecks.io/unity-open-project-1/decks/15-code/card/1a9-pathway-component)
[Forum](https://forum.unity.com/threads/npc-movement-navigation-ai.1051322/)
[treivize](https://github.com/UnityTechnologies/open-project-1/pull/370)
<span style="display:block;text-align:center">
 
</span>

Improvement:
less code
no debug  message
more precise points
Idea of ​​replacing the waypoint with the nearest NavMesh point during the probing phase

### CODE REVIEW

**Comment by AlexandreGheraibia** [comment]
https://user-images.githubusercontent.com/27300700/108023956-edc1cf00-7023-11eb-9349-d30e4d635ca3.mp4

**Comment by AlexandreGheraibia** [comment]
https://user-images.githubusercontent.com/27300700/108025534-ecde6c80-7026-11eb-91c9-2dd0789ee42b.mp4

**Comment by AlexandreGheraibia** [comment]
@ciro-unity, @treivize  incorrect use of EditorGUI.BeginChangeCheck () in PathwayHandles.cs.
correction : 
https://github.com/AlexandreGheraibia/open-project-1/blob/PathwayWithIdea/UOP1_Project/Assets/Scripts/Editor/Pathway/PathwayHandles.cs

**Comment by amel-unity** [comment]
Great improvements and I like the Idea of ​​replacing the waypoint with the nearest NavMesh point. This is good way to make sure when we define a path, a character will not be stuck trying to reach a waypoint if it is not on a walkable area.... 
Thanks a lot for opening the PR, I will merge it now :)

**Comment by amel-unity** [comment]
Great improvements and I like the Idea of ​​replacing the waypoint with the nearest NavMesh point. This is a good way to make sure when we define a path, a character will not be stuck trying to reach a waypoint if it is not on a walkable area....
Thanks a lot for opening the PR, I will merge it now :)

**Comment by AlexandreGheraibia** [comment]
> 
> 
> Great improvements and I like the Idea of ​​replacing the waypoint with the nearest NavMesh point. This is a good way to make sure when we define a path, a character will not be stuck trying to reach a waypoint if it is not on a walkable area....
> Thanks a lot for opening the PR, I will merge it now :)

Thank you, I wouldn't have had the idea without Ciro's return. I had a lot of fun doing this script.

**Pull request merged**
