### PR TITLE
Inventory System continued

### PR DESCRIPTION
**Pull request by circa94**
Regarding thread:
[https://forum.unity.com/threads/inventory-system.980646](https://forum.unity.com/threads/inventory-system.980646)

I've continued working on the inventory system by fixing a bug where now the actual game object is destory when the item is collected and integrated the system in-game.

First thing I did, was moving the files of the inventory system to it's own folder as in the project conventions described
[https://docs.google.com/document/d/1-eUWZ0lWREFu5iH-ggofwnixDDQqalOoT4Yc0NpWR3k/edit](https://docs.google.com/document/d/1-eUWZ0lWREFu5iH-ggofwnixDDQqalOoT4Yc0NpWR3k/edit)

The item type has now again a background color which is required to show in the UI. See https://forum.unity.com/threads/ui-wireframing.987606/#post-6441089
It was accidentaly removed in this [commit](https://github.com/UnityTechnologies/open-project-1/pull/100/commits/cfeecd4bf9520504fbfdc65448142add7e86088b#diff-a1374d376e5589c502bde3bd52a0d3c6e413a1f27cfab84d2dd9d6724b3143a2L17) I guess but is now ont the item type level and not the item itself.

Additionally, I've added a first test ingredient which can be collected when the player is colliding with the item.

I'm not sure if I am allowed to update scenes and/or the existing pig prefab so I did not. If you want to test the collection of an item you need to attach the InventoryController to the pig prefab and assign the player inventory scriptable object. Then drop the salad prefab from Assets/Prefabs/Items into the scene. Otherwise I can update the pig prefab and scene as well.

I'm happy to hear your thoughts

### CODE REVIEW

**Comment by Javimtib92** [comment]
@circa94 Could you add [Serializable] tag to ItemStack? that way the ItemStack List would display properly on the Inventory Scriptable Object inspector :)

**Comment by circa94** [comment]
Update: Items are now visible in the inspector as well

**Comment by ciro-unity** [comment]
Hey @circa94, sorry for the long waiting times! @uChema is working on this PR, she will merge it soon!

**Comment by ciro-unity** [comment]
Hey @circa94, sorry for the late resolution on this one. Chema actually pulled your changes into her branch on her fork before merging them with a lot of new code she wrote, so even though we're closing this specific PR, the code in it has been merged... somehow :P

Thanks!

**Pull request closed without merging**
