### PR TITLE
Pathway component

### PR DESCRIPTION
**Pull request by AlexandreGheraibia**
**Pathway content :**

> - A prefab at the root of Prefabs folder
> - A Pathway script at the root of Script folder
> - A folder Patway  with 5 scripts at the root of Editor folder named **PathwayEditor, PathwayGismos, PathwayHandles, PathwayNavMesh and PathWayNavMeshUI.**
> 
> **PathwayEditor** is a custom editor script that manages the ReorderableList and creates instances of PathwayHandles and PathwayNavMeshUI.
> 
> **PathwayNavMesh** implements polls and the generation of the path by NavMesh.
> 
> > Polls are done by calling NavMesh.SamplePosition for each waypoint with a radius twice the meshSize variable.
> > The navmesh path result is generated by iterating a call to NavMesh.CalculatePath between each waypoint
> > 
> 
> **PathwayGismos** manages the display of the lines and points labels.
> 
> **PathwayHandles** manages the display of the handles.
> 
> **PathWayNavMeshUI**  manages the buttons and associated actions and creates an instance of  .PathwayNavMesh.

### CODE REVIEW

**Comment by AlexandreGheraibia** [comment]
**Pathway contains :**

> - A prefab at the root of Prefabs folder
> - A Pathway script at the root of Script folder
> - A folder Patway  with 4 scripts at the root of Editor folder named **PathwayEditor, PathwayGismos, PathwayHandles, PathwayNavMesh.**
> 
> **PathwayEditor** is a custom editor script that manages the ReorderableList and creates instances of PathwayHandles and PathwayNaveMesh.
> 
> **PathwayNavMesh** manages the buttons and associated actions, polls and the generation of the path by NavMeshPath.
> 
> > Polls are done by calling NavMesh.SamplePosition for each waypoint with a radius twice the meshSize variable.
> > The navmesh path result is generated by iterating a call to NavMesh.CalculatePath between each waypoint
> > 
> 
> **PathwayGismos** manages the display of the different elements.
> 
> **PathwayHandles** manages the display of the handles.

**Comment by AlexandreGheraibia** [comment]
**Pathway contains :**

> - A prefab at the root of Prefabs folder
> - A Pathway script at the root of Script folder
> - A folder Patway  with 4 scripts at the root of Editor folder named **PathwayEditor, PathwayGismos, PathwayHandles, PathwayNavMesh.**
> 
> **PathwayEditor** is a custom editor script that manages the ReorderableList and creates instances of PathwayHandles and PathwayNaveMesh.
> 
> **PathwayNavMesh** manages the buttons and associated actions, polls and the generation of the path by NavMeshPath.
> 
> > Polls are done by calling NavMesh.SamplePosition for each waypoint with a radius twice the meshSize variable.
> > The navmesh path result is generated by iterating a call to NavMesh.CalculatePath between each waypoint
> > 
> 
> **PathwayGismos** manages the display of the different elements.
> 
> **PathwayHandles** manages the display of the handles.

image

**Comment by AlexandreGheraibia** [comment]
**Pathway contains :**

> - A prefab at the root of Prefabs folder
> - A Pathway script at the root of Script folder
> - A folder Patway  with 4 scripts at the root of Editor folder named **PathwayEditor, PathwayGismos, PathwayHandles, PathwayNavMesh.**
> 
> **PathwayEditor** is a custom editor script that manages the ReorderableList and creates instances of PathwayHandles and PathwayNaveMesh.
> 
> **PathwayNavMesh** manages the buttons and associated actions, polls and the generation of the path by NavMeshPath.
> 
> > Polls are done by calling NavMesh.SamplePosition for each waypoint with a radius twice the meshSize variable.
> > The navmesh path result is generated by iterating a call to NavMesh.CalculatePath between each waypoint
> > 
> 
> **PathwayGismos** manages the display of the different elements.
> 
> **PathwayHandles** manages the display of the handles.

image

**Comment by AlexandreGheraibia** [comment]
I have 2 instance of the editor script

**Comment by ciro-unity** [comment]
Thanks Alexandre. A few feedbacks:
- Files need to go in their folders, not on the root of Scripts or Prefabs.
- What's the mesh feature for? I think it could be safely removed, it just creates noise in the scene.
- Also MeshColor, SelectedColor, could be removed?
- "Gismos" should be "Gizmos" (in `PathwayGismos.cs`)
- Is it possible to keep the text close to the point, and make it zoom independent? Right now it shows up a bit of a mess if you zoom out, and if you make it bigger it also goes up
image
- If you add a new point when the navmesh is done, it spams the console with an error message saying "Polls need to be updated"
- The navmesh seems to fail to generate many times... it's hard to make it work.

So yeah, good start but it needs fixing. Why don't you do one thing? You create 1 PR with just the path functionality, so other people can use it to build the AI. And then you open a new one with the Navmesh enhancement?

**Comment by AlexandreGheraibia** [comment]
> 
> 
> Thanks Alexandre. A few feedbacks:
> 
>     * Files need to go in their folders, not on the root of Scripts or Prefabs.
> 
>     * What's the mesh feature for? I think it could be safely removed, it just creates noise in the scene.
> 
>     * Also MeshColor, SelectedColor, could be removed?
> 
>     * "Gismos" should be "Gizmos" (in `PathwayGismos.cs`)
> 
>     * Is it possible to keep the text close to the point, and make it zoom independent? Right now it shows up a bit of a mess if you zoom out, and if you make it bigger it also goes up
>       image
> 
>     * If you add a new point when the navmesh is done, it spams the console with an error message saying "Polls need to be updated"
> 
>     * The navmesh seems to fail to generate many times... it's hard to make it work.
> 
> 
> So yeah, good start but it needs fixing. Why don't you do one thing? You create 1 PR with just the path functionality, so other people can use it to build the AI. And then you open a new one with the Navmesh enhancement?

Thank you Ciro for the feedback
I don't have time this week because I have a job waiting.
At the start, I put the mesh to see the contact areas and to locate the points more easily with the list.
Then I don't know why Navmesh often fails. I could maybe add a try with NavMeshAgent if NavMesh.calculatePath fails.

**Comment by ciro-unity** [comment]
> I don't have time this week because I have a job waiting.

No problem, job takes priority!



> You create 1 PR with just the path functionality ? You mean just the handles and the reoderableList?

Yes, that's what I meant. Alternatively I've seen that @treivize is also working on some navigation stuff, not sure if he is using paths already... maybe you can build on top of his, if there is a path implementation in his PR.

**Comment by treivize** [comment]
Thanks to mention my PR here, actually I was having a look at the PR from Alexandre this evening to see if it could be adapted to custom edit a ScriptableObject.
Doing small changes, it seems to work fine (I am still trying to figure out how to fetch NavMesh for SO, I am not fully sure if it is supported or not)

Here is the changes I have made:
In **Pathway.cs**:
```
[CreateAssetMenu(fileName = "NPCPathway", menuName = "EntityConfig/Pathway")]
public class Pathway : ScriptableObject
````
In **PathwayEditor.cs**:
```
	public void OnSceneGUI(SceneView sceneView)
	{
		_pathwayHandles.DispalyHandles();
		PathwayGizmos.DrawGizmosSelected(_pathway);
	}

        private void OnEnable()
	{
              [...]
              SceneView.duringSceneGui += this.OnSceneGUI;
        }

        private void OnDisable()
	{
              [...]
              SceneView.duringSceneGui -= this.OnSceneGUI;
        }

        private void AddItem(ReorderableList list)
	{
              [...]
              else
	      {
                    list.serializedProperty.InsertArrayElementAtIndex(list.serializedProperty.arraySize);
                    // Vector3 previous = _pathway.transform.position; Do not rely on MB specificities like Transform.
                    Vector3 previous = Vector3.zero;
                    list.serializedProperty.GetArrayElementAtIndex(list.serializedProperty.arraySize - 1).vector3Value = new Vector3(previous.x + 2, previous.y, previous.z + 2);
              }
````

In **PathwayGizmos.cs**:
````
	[DrawGizmo(GizmoType.Selected)]
	private static void DrawGizmosSelected(Pathway pathway, GizmoType gizmoType)
	public static void DrawGizmosSelected(Pathway pathway)
	{
             // Remove all mention of Gizmos.DrawMesh()
        }
````

Here is the result in the editor:
image

**Comment by treivize** [comment]
Make it work by removing the check called PollsNavMesh() when triggering NavMesh Path button. 
It seems that NavMesh.SamplePosition() is not working the same when triggered from SO.
image

**Comment by AlexandreGheraibia** [comment]
> 
> 
> Make it work by removing the check called PollsNavMesh() when triggering NavMesh Path button. (Not sure why this check is needed)
> image

Check called PollsNavMesh() used to determine if there is a NavMesh point ready for waypoints
in the scene.

**Comment by AlexandreGheraibia** [comment]
It works because a NavMesh exists. by increasing the mesh Size you will have the same effect

**Comment by AlexandreGheraibia** [comment]
> 
> 
> Thanks to mention my PR here, actually I was having a look at the PR from Alexandre this evening to see if it could be adapted to custom edit a ScriptableObject.
> Doing small changes, it seems to work fine (I am still trying to figure out how to fetch NavMesh for SO, I am not fully sure if it is supported or not)
> 
> Here is the changes I have made:
> In **Pathway.cs**:
> 
> ```
> [CreateAssetMenu(fileName = "NPCPathway", menuName = "EntityConfig/Pathway")]
> public class Pathway : ScriptableObject
> ```
> 
> In **PathwayEditor.cs**:
> 
> ```
> 	public void OnSceneGUI(SceneView sceneView)
> 	{
> 		_pathwayHandles.DispalyHandles();
> 		PathwayGizmos.DrawGizmosSelected(_pathway);
> 	}
> 
>         private void OnEnable()
> 	{
>               [...]
>               SceneView.duringSceneGui += this.OnSceneGUI;
>         }
> 
>         private void OnDisable()
> 	{
>               [...]
>               SceneView.duringSceneGui -= this.OnSceneGUI;
>         }
> 
>         private void AddItem(ReorderableList list)
> 	{
>               [...]
>               else
> 	      {
>                     list.serializedProperty.InsertArrayElementAtIndex(list.serializedProperty.arraySize);
>                     // Vector3 previous = _pathway.transform.position; Do not rely on MB specificities like Transform.
>                     Vector3 previous = Vector3.zero;
>                     list.serializedProperty.GetArrayElementAtIndex(list.serializedProperty.arraySize - 1).vector3Value = new Vector3(previous.x + 2, previous.y, previous.z + 2);
>               }
> ```
> 
> In **PathwayGizmos.cs**:
> 
> ```
> 	[DrawGizmo(GizmoType.Selected)]
> 	private static void DrawGizmosSelected(Pathway pathway, GizmoType gizmoType)
> 	public static void DrawGizmosSelected(Pathway pathway)
> 	{
>              // Remove all mention of Gizmos.DrawMesh()
>         }
> ```
> 
> Here is the result in the editor:
> image

https://learn.unity.com/tutorial/creating-custom-gizmos-for-development-2019-2#5fa30655edbc2a0021921053

**Comment by AlexandreGheraibia** [comment]
In PathwayEditor.cs:
```
public void OnSceneGUI()
{
    _pathwayHandles.DispalyHandles();
    _pathwayGizmos.DrawHandlesPath();
}

```

```
private void OnEnable()
{
    [...]
    _pathwayGizmos = new PathwayGizmos(_pathway);
}

```


In PathwayGizmos.cs  erase all static

```
private Pathway _pathway;

public PathwayGizmos(Pathway pathway) {
  _pathway = pathway;
}

public void DrawHandlesPath()

```

**Pull request closed without merging**
