### PR TITLE
Created hammer model and texture

### PR DESCRIPTION
**Pull request by erizzoalbuquerque**
card: https://open.codecks.io/unity-open-project-1/decks/16-3d-shading/card/17i-accessories-for-townsfolk
fórum: https://forum.unity.com/threads/accessories-for-the-townsfolk.1007900/

A small hammer to be used as a tool for the townsfolk.

This is my first experience modeling and texturing. Any feedback is very welcome. 

Hammer And TownFolks

Hammer

### CODE REVIEW

**Comment by ciro-unity** [comment]
Nice!!

**Comment by ciro-unity** [comment]
Little scolding: you haven't named the mesh!! 😁 
image

**Comment by erizzoalbuquerque** [comment]
Oh! Sorry hehe. First time doing this kind of thing. I'm working in another branch right now but soon I'll fix this and I'll commit here.
Thanks for the feedback :)

**Comment by ciro-unity** [comment]
No don't worry, I'll merge it as it is. No big deal in fixing it this time (as I don't think we'll modify the mesh).

**Pull request merged**
