### PR TITLE
Create silhouette pass

### PR DESCRIPTION
**Pull request by shuttle127**
**Issue Card**: https://open.codecks.io/unity-open-project-1/decks/16-3d-shading/card/192-silhouette-pass-for-when-the-player-is-obstructed-by-scenery

**Forum Thread**: N/A

**Issue Resolved**: #24

**Solution**: Added some URP render features to silhouette characters when they're behind static scenery. Per instructions given by @ciro-unity in comments for #50, including [this tutorial video](https://www.youtube.com/watch?v=szsWx9IQVDI), created a Characters layer and added basic unlit shader solution without the dither but with a basic Fresnel Effect (who doesn't like that word and look anyway?).

**Verification**: Run the TestingGround scene and move Hamlet behind the big rock to see the effects. Also check out these screenshots:

Chop Chop Occlusion Silhouette 1

Chop Chop Occlusion Silhouette 2

Chop Chop Occlusion Silhouette 3

Chop Chop Occlusion Silhouette 4

### CODE REVIEW

**Comment by erizzoalbuquerque** [comment]
Hey! Very Good work, @shuttle127 !

But I'm not sure about the visuals. It looks a lot like the shadows. I can't easily and quickly differentiate an occluded object from a shadow. You could use dithering, transparency, or maybe a different color. Anything visually different from the shadow. What do you think?

**Comment by shuttle127** [comment]
I agree it does look like the shadows a bit too much, tried to take Ciro’s original suggestion verbatim but wasn’t sure exactly what flat color meant and was hoping for feedback like this since I had very little time to put this together. I was thinking more a grayish color with dither would look cool, should I take that next step or is there a better look to shoot for?

**Comment by ciro-unity** [comment]
Super cool! Thanks for this, @shuttle127! And glad you finally joined us on the dark side of the project (Github) :D
I agree full black is easy to confuse with the shadow, but as you say from here the colour is easy to change. I'll make a few tests and tweak it.

**Comment by ciro-unity** [comment]
LOL. First tests are not promising 😆 
image

(I'm investigating)

**Comment by ciro-unity** [comment]
OK, I imagine you didn't hit Save Project before sending the changes, so the `ToonRendererData` didn't contain a reference to the material.

There were a couple of things I fixed too. For instance the eyes were not part of this process, since they are on the transparent queue. So I added yet another pass to address them.

Also I made the shader with dither. We can change it later, but for now it looks good and not too intrusive.

I think it turned out pretty nice?

image

**Comment by ciro-unity** [comment]
Merged!

**Comment by shuttle127** [comment]
Looks great, thanks for cleaning up my beginner’s mess rush job, heh.

**Pull request merged**
