### PR TITLE
Added Conventions Link to README

### PR DESCRIPTION
**Pull request by davejrodriguez**
Currently, project conventions exist, but are buried [here](https://forum.unity.com/threads/vote-for-coding-standards.980337/page-2#post-6392942) on the second page of the thread. Displaying it in the README will provide relevant information for those looking to contribute.

### CODE REVIEW

**Comment by ciro-unity** [comment]
Thanks Dave, I included the link and I just reworded a few things in the Readme before merging.

**Comment by ciro-unity** [comment]
I'm a bit confused as to why in the history of commits for this PR there's stuff from another PR (#90?)
But it seems like the change is only to the readme, right?

**Comment by davejrodriguez** [comment]
Yeah, forgot to use a branch, so a bunch of history came along that I reverted. Only the README is changed in this PR. And I _think_, if you use squash, the history will not be visible(?), just the actual changes. Though I'm not entirely familiar with that git command.

**Comment by ciro-unity** [comment]
I'm not sure if there's the need for a new PR. I think in terms of changes it should be ok, and as you said the whole history should be compacted. I was only confused because when I press "Squash and merge", I get this history:

> * Update README.md
>
>Added a permanent and non-capped invite link to the #open-projects Discord channel on the Official Unity Discord server.
>
>* Added bases for sound manager
>- Created SoundEmitter with basic functionality of playing sounds for further extension
>- Created singleton SoundManager with following functionality:
>    - Change, save and load volume of a selected audio mixer
>    - Managing a pool of SoundEmitter objects with dynamic extension
>    - Playing 2D and Spatial sounds through SoundEmitter
>
>* Changed mixer group functions as static
>
>* Fixes proposed by Deragaun
>- Removed some old testing code
>- Renamed variable thisAudioSource to follow with more formal code guidelines
>- Removed usage of Vector3.zero as a marker for spartialBlend and used the current functionality provided by >AudioSource via parameter
>
>* Renamed variable audioSource to follow convention
>
>* Streamlined Play2DSound so spatialBlend is not needed as a parameter
>...

And so on. But I guess it's ok and that's the whole point: because I'm squashing, the commit message will contain the whole history... (?)

**Comment by davejrodriguez** [comment]
Hmm from what I was reading, it looked like GitHub would allow you to give a new title and description to the squashed commit, but maybe I misunderstood. Is the message not editable? Not the end of the world I guess. I'll be sure to use a branch next time.

**Comment by ciro-unity** [comment]
Yep, I could edit the message. I did, and it seems like everything was squashed correctly into one commit and 1 file changed.

**Pull request merged**
